[build]
  cmd = "go build -ldflags \"-s -w\" -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "toml", "yaml"]
  exclude_dir = ["web", "tmp", ".git", "vendor"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500
  poll = true
  poll_interval = 1000

[log]
  time = true

[misc]
  clean_on_exit = true
